#!/usr/bin/env python3
"""
One self-contained HTML audit report, for any checker.

Every static checker eventually wants the same page: a stat strip, a sticky
toolbar with a search box and severity chips, a list of units each carrying
its findings, and an optional notes panel at the bottom. Writing that page
once per checker means four near-identical copies of ~450 lines of CSS and JS,
which is how the copies quietly drift apart.

This module owns the page. A checker's report script converts its own result
dict into the neutral shape below and calls render_html(); it never touches
markup.

    from audit_report_html import Finding, Group, Stat, render_html

    render_html(
        out_path="reports/my_audit.html",
        title="Code rule audit",
        eyebrow="Acme · code_rule_checker",
        meta_html="Scanned <b>src/</b> · <b>42</b> units · rules v<b>1.0.0</b>",
        stats=[Stat("Units", 42), Stat("Clean", 30, tone="clean"),
               Stat("Errors", 3, tone="error")],
        groups=[Group(id="parser", sublabel="src/parser", counts={"error": 1},
                      findings=[Finding("error", "max-file-lines",
                                        "src/parser/Big.cs", "File is 812 lines")])],
        group_noun="unit",
        notes_title="2 rule(s) require manual review",
        notes=[("no-vendor-patching", "Needs the diff, not a snapshot.")],
        footer="Generated by scripts/my_report.py — re-run to refresh.",
    )

The page is a single file with no external requests: theme-aware (light, dark,
and an explicit data-theme override), responsive, and filterable offline.
"""
import json
from html import escape as html_escape
from pathlib import Path

SEVERITIES = ("error", "warning", "info")


class Stat:
    """One cell of the stat strip. tone tints the number: None, "clean",
    "error", "warning" or "info"."""

    def __init__(self, label, value, tone=None):
        self.label = label
        self.value = value
        self.tone = tone

    def as_dict(self):
        return {"label": self.label, "value": self.value, "tone": self.tone or ""}


class Finding:
    """One row inside a group. severity must be one of SEVERITIES; label is
    the rule id or check name; location is a file path (with :line already
    appended if there is one)."""

    def __init__(self, severity, label, location, message):
        if severity not in SEVERITIES:
            raise ValueError(f"severity must be one of {SEVERITIES}, got {severity!r}")
        self.severity = severity
        self.label = label
        self.location = location
        self.message = message

    def as_dict(self):
        return {"severity": self.severity, "label": self.label,
                "location": self.location or "", "message": self.message}


class Group:
    """One unit of the report — a module, package, file, test, whatever the
    checker's unit of work is. counts is {severity: n}; anything missing is 0.
    'clean' defaults to "no error and no warning findings"."""

    def __init__(self, id, sublabel="", findings=None, counts=None, clean=None):
        self.id = id
        self.sublabel = sublabel
        self.findings = list(findings or [])
        self.counts = {s: (counts or {}).get(s, 0) for s in SEVERITIES}
        if counts is None:
            for f in self.findings:
                self.counts[f.severity] += 1
        self.clean = (self.counts["error"] == 0 and self.counts["warning"] == 0) if clean is None else clean

    def as_dict(self):
        return {"id": self.id, "sublabel": self.sublabel, "clean": self.clean,
                "counts": self.counts, "findings": [f.as_dict() for f in self.findings]}


def render_html(out_path, title, eyebrow, meta_html, stats, groups,
                group_noun="unit", notes_title="", notes=None, footer=""):
    """Writes the report and returns its Path. 'notes' is a list of
    (label, text) pairs for the bottom panel — use it for checks that could
    not be automated, or for anything that isn't a per-unit finding. The panel
    hides itself when the list is empty."""
    payload = {
        "title": title,
        "eyebrow": eyebrow,
        "metaHtml": meta_html,
        "groupNoun": group_noun,
        "groupNounPlural": group_noun + "s",
        "stats": [s.as_dict() for s in stats],
        "groups": [g.as_dict() for g in groups],
        "notesTitle": notes_title,
        "notes": [{"label": label, "text": text} for label, text in (notes or [])],
        "footer": footer,
    }
    # </script> inside any string would close the data block early.
    data = json.dumps(payload).replace("</", "<\\/")
    # The <title> tag is filled in statically as well as by the script: some
    # readers (an artifact host, a tab title before JS runs) only see the tag.
    page = (_TEMPLATE
            .replace("__TITLE_PLACEHOLDER__", html_escape(title))
            .replace("__REPORT_DATA__", data))
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(page, encoding="utf-8")
    return out_path


# Le gabarit de la page vit dans son propre fichier, à côté : du HTML, du CSS et
# du JavaScript n'ont rien à faire dans une chaîne Python.
_TEMPLATE = Path(__file__).with_name("audit_report.html").read_text(encoding="utf-8")
